version: "3"

services:
  php:
    container_name: "php"
    image: php:7.4-fpm
    build:
      args:
        uid: 1000
        user: usuário_da_máquina_host
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
    ports:
      - "9000:9000"
    # restart: always
    networks:
      - mynetwork

  nginx:
    container_name: "nginx"
    image: nginx:1.19
    volumes:
      - ./docker/nginx/server.pem:/etc/nginx/ssl/server.pem
      - ./docker/nginx/server-key.pem:/etc/nginx/ssl/server-key.pem
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    ports:
      - "80:80"
      - "443:443"
    # restart: always
    networks:
      - mynetwork

  mariadb:
    container_name: "mariadb"
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    # restart: unless-stopped
    networks:
      - mynetwork

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin:5.1
    environment:
      PMA_HOST: mariadb
    # restart: unless-stopped
    links:
      - "mariadb"
    ports:
      - "3380:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
