version: "3"

services:
  php:
    container_name: "php-srv"
    image: php:7.4-fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    # restart: always
    networks:
      - mynetwork

  nginx:
    container_name: "nginx-srv"
    image: nginx:1.19
    volumes:
      - ./docker/nginx/server.pem:/etc/nginx/ssl/server.pem
      - ./docker/nginx/server-key.pem:/etc/nginx/ssl/server-key.pem
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - "80:80"
      - "443:443"
    # restart: always
    networks:
      - mynetwork

  pgsql:
    container_name: "mariadb-srv"
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    # restart: unless-stopped
    networks:
      - mynetwork

  postgres:
    container_name: postgres-srv
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/pgsql:/var/lib/postgresql/data
    # restart: unless-stopped
    networks:
      - mynetwork

  mariadb:
    container_name: "mariadb-srv"
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    # restart: unless-stopped
    networks:
      - mynetwork

  mysql:
    container_name: mysql-srv
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    # restart: unless-stopped
    networks:
      - mynetwork

  phpmyadmin:
    container_name: "phpmyadmin-srv"
    image: phpmyadmin:5.1
    environment:
      PMA_HOST: mariadb
    # restart: unless-stopped
    links:
      - "mariadb"
    ports:
      - "3380:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
