version: "3"

services:
  php:
    build: ./docker/php
    image: php:7.4
    container_name: "php"
    volumes:
      - ./www:/var/www
    ports:
      - "9000:9000"
    # restart: always
    networks:
      - mynetwork

  nginx:
    image: nginx:1.19
    container_name: "nginx"
    volumes:
      - ./docker/nginx/server.pem:/etc/nginx/ssl/server.pem
      - ./docker/nginx/server-key.pem:/etc/nginx/ssl/server-key.pem
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    ports:
      - "80:80"
      - "443:443"
    # restart: always
    networks:
      - mynetwork

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    # restart: unless-stopped
    networks:
      - mynetwork

  # mysql:
  #   image: mysql:5.6
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./docker/mysql:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   # restart: unless-stopped
  #   networks:
  #     - mynetwork

  phpmyadmin:
    image: phpmyadmin:5.0
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
    # restart: unless-stopped
    links:
      - "mariadb"
    ports:
      - "3380:80"
    networks:
      - mynetwork

  # postgres:
  #   image: postgres:12
  #   container_name: "postgres"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./docker/pgsql:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: "postgres"
  #   # restart: always
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
    driver: bridge
